# Generated by Django 3.1.1 on 2020-09-10 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='acoes',
            name='voluntario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.voluntario'),
            preserve_default=False,
        ),
    ]
