# Generated by Django 3.1.1 on 2020-09-12 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_auto_20200912_0922"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voluntario",
            name="acao",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="voluntarios",
                to="core.acao",
            ),
            preserve_default=False,
        ),
    ]
