# Generated by Django 3.1.1 on 2020-09-10 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_acoes_voluntario'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Acoes',
            new_name='Acao',
        ),
    ]
